// ngon.js
// Generalized n-gon geometry using floating-point arithmetic.
// For n=5 this reproduces the pentagon lattice (approximately).
// Also supports the Sierpiński triangle IFS mode.
//
// A "tile" in the generalized sense is:
//   { centroid: [x,y], orient: int (0..n-1), sigma: int (0/1),
//     verts: [[x,y],...], n: int }
//
// For Sierpiński mode, tiles are triangles at various scales/positions
// produced by the IFS { f_k(x) = x/2 + p_k } for k=0,1,2.

// ── Helpers ──────────────────────────────────────────────────────────────────

export function mod(a, n) {
  return ((a % n) + n) % n;
}

// Rotate a 2D point by angle (radians) around origin.
export function rot2(x, y, angle) {
  const c = Math.cos(angle), s = Math.sin(angle);
  return [c * x - s * y, s * x + c * y];
}

// ── Regular n-gon ─────────────────────────────────────────────────────────────

/**
 * Circumradius of a regular n-gon with unit edge length.
 * R = 1 / (2 * sin(π/n))
 */
export function circumradius(n) {
  return 1 / (2 * Math.sin(Math.PI / n));
}

/**
 * Apothem (inradius) of a regular n-gon with unit edge length.
 * a = 1 / (2 * tan(π/n))
 */
export function apothem(n) {
  return 1 / (2 * Math.tan(Math.PI / n));
}

/**
 * Vertices of a regular n-gon centred at (cx,cy) with circumradius R,
 * rotated so that vertex 0 is at angle `startAngle` from centre.
 * sigma=0: vertex 0 up (startAngle = π/2)
 * sigma=1: vertex 0 down (startAngle = -π/2)
 * orient: additional rotation by orient*(2π/n)
 */
export function ngonVertices(cx, cy, n, orient, sigma) {
  const R = circumradius(n);
  const baseAngle = sigma === 0 ? Math.PI / 2 : -Math.PI / 2;
  const verts = [];
  for (let k = 0; k < n; k++) {
    const angle = baseAngle + (orient + k) * (2 * Math.PI / n);
    verts.push([cx + R * Math.cos(angle), cy + R * Math.sin(angle)]);
  }
  return verts;
}

/**
 * Edge midpoint k of an n-gon tile.
 */
export function edgeMidpoint(cx, cy, n, orient, sigma, k) {
  const verts = ngonVertices(cx, cy, n, orient, sigma);
  const v0 = verts[k];
  const v1 = verts[(k + 1) % n];
  return [(v0[0] + v1[0]) / 2, (v0[1] + v1[1]) / 2];
}

/**
 * Compute the neighbour of an n-gon tile across edge k.
 * Returns { centroid, orient, sigma, matchEdge }.
 *
 * The neighbour's centroid is the reflection of the current centroid
 * through the edge midpoint:
 *   c' = 2*mid - c
 *
 * For odd n: sigma flips (necessary for edge-to-edge fit).
 * For even n: sigma stays (180° rotation suffices).
 *
 * The orient shift is chosen so that the neighbour's matching edge
 * lines up with edge k of the current tile.
 */
export function ngonNeighbour(cx, cy, n, orient, sigma, k) {
  const [mx, my] = edgeMidpoint(cx, cy, n, orient, sigma, k);
  const ncx = 2 * mx - cx;
  const ncy = 2 * my - cy;

  // For odd n, sigma must flip for the shared edge to match.
  // For even n, a pure rotation by π about the midpoint works.
  const newSigma = (n % 2 === 1) ? 1 - sigma : sigma;

  // Find orient shift: try all n values and pick the one where
  // the neighbour's edge kk shares the same midpoint as edge k of self.
  // We use the midpoint criterion (fast, no vertex enumeration needed).
  const [emx, emy] = [mx, my]; // target midpoint
  let bestOrient = 0;
  let bestMatchEdge = 0;
  let bestDist = Infinity;

  for (let dO = 0; dO < n; dO++) {
    const nO = mod(orient + dO, n);
    for (let kk = 0; kk < n; kk++) {
      const [mmx, mmy] = edgeMidpoint(ncx, ncy, n, nO, newSigma, kk);
      const d = (mmx - emx) ** 2 + (mmy - emy) ** 2;
      if (d < bestDist) {
        bestDist = d;
        bestOrient = nO;
        bestMatchEdge = kk;
      }
    }
  }

  return {
    centroid: [ncx, ncy],
    orient: bestOrient,
    sigma: newSigma,
    matchEdge: bestMatchEdge,
  };
}

/**
 * Canonical string key for a tile position/orientation.
 * We snap to 9 decimal places to absorb floating-point drift.
 */
export function tileKey(cx, cy, orient, sigma) {
  const snap = (v) => Math.round(v * 1e7) / 1e7;
  return `${snap(cx)},${snap(cy)}|o${orient}|s${sigma}`;
}

// ── Sierpiński Triangle IFS ───────────────────────────────────────────────────

/**
 * The Sierpiński triangle is generated by the IFS:
 *   f_0(x,y) = (x/2,       y/2)
 *   f_1(x,y) = (x/2 + 1/2, y/2)
 *   f_2(x,y) = (x/2 + 1/4, y/2 + √3/4)
 *
 * We represent each triangle by its bottom-left corner (bx,by) and
 * its scale s (edge length = s). The three sub-triangles of a triangle
 * at (bx,by,s) are at:
 *   (bx,       by,       s/2)
 *   (bx+s/2,   by,       s/2)
 *   (bx+s/4,   by+h/2,   s/2)   where h = s*√3/2
 *
 * We build the tree to a given depth and return flat tile objects
 * compatible with the lattice format.
 */
const SQRT3 = Math.sqrt(3);

export function buildSierpinski(depth) {
  // Root triangle: unit equilateral, bottom-left at (-0.5, -√3/6)
  // so centroid is at origin.
  const rootBx = -0.5;
  const rootBy = -SQRT3 / 6;
  const rootS = 1.0;

  const tiles = [];
  const byId = new Map();

  function triVerts(bx, by, s) {
    const h = s * SQRT3 / 2;
    return [
      [bx,           by    ],
      [bx + s,       by    ],
      [bx + s / 2,   by + h],
    ];
  }

  function triCentroid(bx, by, s) {
    const h = s * SQRT3 / 2;
    return [bx + s / 2, by + h / 3];
  }

  function snapKey(bx, by, s) {
    const r = (v) => Math.round(v * 1e8) / 1e8;
    return `${r(bx)},${r(by)},${r(s)}`;
  }

  // BFS / recursive expansion
  function expand(bx, by, s, d, parentIdx, childEdge) {
    const id = snapKey(bx, by, s);
    if (byId.has(id)) return byId.get(id);

    const idx = tiles.length;
    const [cx, cy] = triCentroid(bx, by, s);
    const verts = triVerts(bx, by, s);
    const tile = {
      index: idx,
      id,
      // Sierpinski tiles use sheet=0 always (no multi-sheet structure),
      // but we assign a "level" as the depth for coloring.
      centroid: [cx, cy],
      centroidF: [cx, cy],
      orient: 0,
      sigma: 0,
      sheet: d % 5,   // use depth mod 5 for color variety
      depth: d,
      verts,
      vertsF: verts,
      neighbors: [null, null, null],
      neighborSheetDeltas: [0, 0, 0],
      // Sierpinski-specific
      bx, by, s,
      isSierpinski: true,
      n: 3,
    };
    tiles.push(tile);
    byId.set(id, idx);
    return idx;
  }

  // Build tree recursively.
  function buildTree(bx, by, s, d) {
    const idx = expand(bx, by, s, d, -1, -1);
    if (d >= depth) return idx;

    const h = s * SQRT3 / 2;
    const ns = s / 2;
    const children = [
      [bx,           by,       ns],
      [bx + ns,      by,       ns],
      [bx + ns / 2,  by + h / 2, ns],
    ];

    for (let k = 0; k < 3; k++) {
      const [cbx, cby, cs] = children[k];
      const cIdx = buildTree(cbx, cby, cs, d + 1);
      tiles[idx].neighbors[k] = cIdx;
    }
    return idx;
  }

  buildTree(rootBx, rootBy, rootS, 0);

  // Also link leaf-level siblings (same parent, adjacent edges).
  // For simplicity we leave sibling links as null; the CA will still
  // work using parent→child links.

  return { tiles, byId, groupOrder: 5, radius: depth, isSierpinski: true, n: 3 };
}

// ── Lattice builder for regular n-gons ───────────────────────────────────────

export function buildNgonLattice({ n = 5, radius = 3, groupOrder = 5 } = {}) {
  const tiles = [];
  const byId = new Map();

  function addTile(cx, cy, orient, sigma, sheet, depth) {
    const id = tileKey(cx, cy, orient, sigma) + `|sh${sheet}`;
    if (byId.has(id)) return byId.get(id);
    const idx = tiles.length;
    const verts = ngonVertices(cx, cy, n, orient, sigma);
    const tile = {
      index: idx,
      id,
      centroid: [cx, cy],
      centroidF: [cx, cy],
      orient,
      sigma,
      sheet,
      depth,
      verts,
      vertsF: verts,
      neighbors: new Array(n).fill(null),
      neighborSheetDeltas: new Array(n).fill(0),
      n,
      isSierpinski: false,
    };
    tiles.push(tile);
    byId.set(id, idx);
    return idx;
  }

  const originIdx = addTile(0, 0, 0, 0, 0, 0);
  const queue = [originIdx];

  while (queue.length > 0) {
    const tIdx = queue.shift();
    const t = tiles[tIdx];

    for (let k = 0; k < n; k++) {
      if (t.neighbors[k] !== null) continue;

      const nb = ngonNeighbour(t.centroid[0], t.centroid[1], n, t.orient, t.sigma, k);
      const delta = k % groupOrder;
      const newSheet = mod(t.sheet + delta, groupOrder);
      const [ncx, ncy] = nb.centroid;
      const id = tileKey(ncx, ncy, nb.orient, nb.sigma) + `|sh${newSheet}`;

      let nIdx;
      if (byId.has(id)) {
        nIdx = byId.get(id);
      } else if (t.depth < radius) {
        nIdx = addTile(ncx, ncy, nb.orient, nb.sigma, newSheet, t.depth + 1);
        queue.push(nIdx);
      } else {
        continue;
      }

      t.neighbors[k] = nIdx;
      t.neighborSheetDeltas[k] = delta;

      // Back-link: find the matching edge on the neighbour.
      const nt = tiles[nIdx];
      if (nt.neighbors[nb.matchEdge] === null) {
        nt.neighbors[nb.matchEdge] = tIdx;
        nt.neighborSheetDeltas[nb.matchEdge] = mod(-delta, groupOrder);
      }
    }
  }

  return { tiles, byId, groupOrder, radius, n, isSierpinski: false };
}

// ── Field info strings ────────────────────────────────────────────────────────

export function fieldInfoForN(n) {
  const fields = {
    3:  { field: "ℚ(√3)",        group: "ℤ₆",  result: "Periodic lattice (d=2)" },
    4:  { field: "ℚ",            group: "ℤ₄",  result: "Periodic lattice (d=2)" },
    5:  { field: "ℚ(√5)",        group: "ℤ₅",  result: "Multi-sheeted (2<d<3)" },
    6:  { field: "ℚ(√3)",        group: "ℤ₆",  result: "Periodic lattice (d=2)" },
    7:  { field: "ℚ(cos 2π/7)",  group: "ℤ₇",  result: "Non-reconnective (tree)" },
    8:  { field: "ℚ(√2)",        group: "ℤ₈",  result: "Quasicrystal / multi-sheeted" },
    9:  { field: "ℚ(cos 2π/9)",  group: "ℤ₉",  result: "Non-reconnective (tree)" },
    10: { field: "ℚ(√5)",        group: "ℤ₁₀", result: "Quasicrystal / multi-sheeted" },
    12: { field: "ℚ(√3)",        group: "ℤ₁₂", result: "Periodic lattice (d=2)" },
  };
  return fields[n] || {
    field: `ℚ(cos 2π/${n})`,
    group: `ℤ${n}`,
    result: "Non-reconnective (tree)",
  };
}

export const POLY_PRESETS = {
  triangle:   { n: 3,  label: "Equilateral Triangle" },
  square:     { n: 4,  label: "Square" },
  pentagon:   { n: 5,  label: "Regular Pentagon" },
  hexagon:    { n: 6,  label: "Regular Hexagon" },
  heptagon:   { n: 7,  label: "Regular Heptagon" },
  octagon:    { n: 8,  label: "Regular Octagon" },
  decagon:    { n: 10, label: "Regular Decagon" },
  dodecagon:  { n: 12, label: "Regular Dodecagon" },
};